# Generated by Django 5.0.1 on 2024-01-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='mark',
            field=models.SmallIntegerField(),
        ),
    ]
