# Generated by Django 5.0.1 on 2024-02-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_card_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardProduct',
            new_name='CartProduct',
        ),
    ]
