# Generated by Django 5.0.1 on 2024-02-03 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_cardproduct_cartproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='card',
            new_name='cart',
        ),
    ]
