# Generated by Django 5.0.2 on 2024-02-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_enterproduct_quantity_enter_notation'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterproduct',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
